import { library } from "@fortawesome/fontawesome-svg-core";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";

// Two subsets are pulled in: the bulk of the app uses the solid set,
// and a small number of icons (currently just bookmark) need the
// regular outline pair so we can render filled vs unfilled states.
// Aliased on import so the solid + regular versions of the same glyph
// don't collide in scope. The cast on `library.add()` below pins the
// regular icon to the core's IconDefinition type — the two subset
// packages export structurally-identical but nominally-distinct
// IconDefinitions, which trips library.add()'s variadic typing.
import {
  faBookmark as farBookmark,
} from "@fortawesome/free-regular-svg-icons";

import {
  faArrowDown,
  faArrowCircleDown,
  faArrowLeft,
  faArrowRight,
  faArrowRotateRight,
  faArrowUp,
  faArrowCircleUp,
  faBell,
  faBolt,
  faBookmark,
  faBullseye,
  faCaretDown,
  faCaretUp,
  faChartPie,
  faChevronRight,
  faCircleCheck,
  faCircleExclamation,
  faCircleNodes,
  faCircleNotch,
  faCircleQuestion,
  faClockRotateLeft,
  faCodeBranch,
  faCompass,
  faComputer,
  faDatabase,
  faDownload,
  faExclamationTriangle,
  faEye,
  faEyeSlash,
  faGaugeHigh,
  faGlobe,
  faGlobeEurope,
  faHardDrive,
  faHeartPulse,
  faKey,
  faLaptop,
  faLifeRing,
  faLink,
  faListCheck,
  faListOl,
  faListUl,
  faMagnifyingGlass,
  faMemory,
  faMicrochip,
  faMoon,
  faNetworkWired,
  faPause,
  faPen,
  faPenToSquare,
  faPlay,
  faPlug,
  faPlus,
  faPowerOff,
  faServer,
  faShieldHalved,
  faStopwatch,
  faSun,
  faTowerBroadcast,
  faTableList,
  faTachometer,
  faTachometerAlt,
  faTerminal,
  faTrash,
  faTriangleExclamation,
  faUpload,
  faUpRightFromSquare,
  faWaveSquare,
  faWifi,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  // Solid
  faArrowDown,
  faArrowCircleDown,
  faArrowLeft,
  faArrowRight,
  faArrowRotateRight,
  faArrowUp,
  faArrowCircleUp,
  faBell,
  faBolt,
  faBookmark,
  faBullseye,
  faCaretDown,
  faCaretUp,
  faChartPie,
  faChevronRight,
  faCircleCheck,
  faCircleExclamation,
  faCircleNodes,
  faCircleNotch,
  faCircleQuestion,
  faClockRotateLeft,
  faCodeBranch,
  faCompass,
  faComputer,
  faDatabase,
  faDownload,
  faExclamationTriangle,
  faEye,
  faEyeSlash,
  faGaugeHigh,
  faGlobe,
  faGlobeEurope,
  faHardDrive,
  faHeartPulse,
  faKey,
  faLaptop,
  faLifeRing,
  faLink,
  faListCheck,
  faListOl,
  faListUl,
  faMagnifyingGlass,
  faMemory,
  faMicrochip,
  faMoon,
  faNetworkWired,
  faPause,
  faPen,
  faPenToSquare,
  faPlay,
  faPlug,
  faPlus,
  faPowerOff,
  faServer,
  faShieldHalved,
  faStopwatch,
  faSun,
  faTowerBroadcast,
  faTableList,
  faTachometer,
  faTachometerAlt,
  faTerminal,
  faTrash,
  faTriangleExclamation,
  faUpload,
  faUpRightFromSquare,
  faWaveSquare,
  faWifi,
);

// Regular (outline) — paired with their solid counterparts above.
// Used by toggle UIs that need a filled/unfilled distinction.
library.add(farBookmark as IconDefinition);
