import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faArrowDown,
  faArrowCircleDown,
  faArrowUp,
  faArrowCircleUp,
  faBolt,
  faCaretDown,
  faCaretUp,
  faCodeBranch,
  faDownload,
  faExclamationTriangle,
  faGaugeHigh,
  faHardDrive,
  faHeartPulse,
  faListUl,
  faMemory,
  faMicrochip,
  faMoon,
  faPause,
  faPlay,
  faServer,
  faSun,
  faTowerBroadcast,
  faTachometer,
  faTachometerAlt,
  faUpload,
  faWaveSquare,
  faWifi,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  // Solid
  faArrowDown,
  faArrowCircleDown,
  faArrowUp,
  faArrowCircleUp,
  faBolt,
  faCaretDown,
  faCaretUp,
  faCodeBranch,
  faDownload,
  faExclamationTriangle,
  faGaugeHigh,
  faHardDrive,
  faHeartPulse,
  faListUl,
  faMemory,
  faMicrochip,
  faMoon,
  faPause,
  faPlay,
  faServer,
  faSun,
  faTowerBroadcast,
  faTachometer,
  faTachometerAlt,
  faUpload,
  faWaveSquare,
  faWifi,
);
